### ISSUE TITLE
gcal.ipynb "collapsed": false, (line 12) doesn't run

### ISSUE THREAD

**Issue by chris-english** [ioam/topographica#537]
changing
"collapsed": false, to "collapsed": "false",
line 12 on my editor
allows the notebook to load.

**Comment by MartinThoma** [comment]
I just had exactly the same problem. It was easy to fix:

* Start `ipython notebook` (not your notebook, but exactly this command)
* Select the notebook in the browser.

**Comment by jbednar** [comment]
That's right -- ipython can't run .ipynb files, but "ipython notebook" can.  It would be very convenient if you could run a notebook just by doing "ipython file.ipynb"; which would be a feature request that you could submit to the ipython folks!  I personally think notebooks *should* be runnable from the commandline, but doing so is currently not terribly easy.
