### ISSUE TITLE
Repeated Numpy warning: Using deprecated NumPy API

### ISSUE THREAD

**Issue by davidljung** [ioam/topographica#559]
Hello.
After following the directions for 'installing' topographica from github on Ubuntu 14.04 LTS, I receive repeated Numpy warnings.  I installed the dependencies using apt-get and cloned the repositories.

I can run an interactive session by invoking ./topographica and the session outputs:

```
$ ./topographica -a -c "generate_example('gcal_10000.typ')"``
...
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/ubuntu/.cache/scipy/python27_compiled/sc_0c2671ff316a54a9e8e81f695ff0bf8c0.cpp:22:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
```

This is running in a newly installed Ubuntu AWS EC2 instance.

**Comment by quantum6** [comment]
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

**Comment by jbednar** [comment]
Sure, you can define that, but in this case the warnings are generated from the underlying weave library, not from topographica, so the way to fix it with #define would have to be to recompile weave, not topographica.  That's not something we'd do in this project...
