### ISSUE TITLE
Saccade_demo.ty fails to load on name NORMAL

### ISSUE THREAD

**Issue by chris-english** [ioam/topographica#620]
topographica 0.9.8-1469-g6b7904d-dirty

Saccade_demo.ty line 22 calls

22 from param.parameterized import VERBOSE,NORMAL,DEBUG
and fails on NORMAL as it appears NORMAL  is no longer a param.parameterized option.

Removing NORMAL from line 22 and changing lines 45, 47 to either VERBOSE or DEBUG

45 SaccadeController.print_level = DEBUG 

47 ShiftingGeneratorSheet.print_level =DEBUG

allows demo to run without complaint

**Comment by jbednar** [comment]
Thanks!  Fixed in 5565b71.
