### ISSUE TITLE
the data used to plot orientation preference map and pinwheels ?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#627]
Dear Bednar,
I am trying to collect data to analyze orientation maps and pinwheels and I use including:
topo.sim.run(1000)
p=topo.sim.V1.views.maps.OrientationPreference.last.data
s=topo.sim.V1.views.maps.OrientationSelectivity.last.data
for every time recording, which means collecting data for every 1000 iteration map matrix.
Then I compare the ploted maps with GCAL_Tutorial in .doc with running notebook.  In this
tutorial, I also run the same script. As shwon there, data=topo.sim.views,  pref=data.OrientationPreference.V1, sel=data.OrientationSelectivity.V1. Also I  run data.Pinwheels.V1. But for every 1000 iteration snapshot, the map shown in the tutorial and the one
from using the collected data are not the same.  I am puzzled by this and maybe the data I collected is not the same ?

**Comment by jbednar** [comment]
Sorry -- for some reason I didn't see this issue come in!  The detailed shape of the map is affected by lots of things, and I'm not sure which particular simulation you were running.  Any change in the random streams of inputs will give a different random shape to the map.  If you wanted to post more detail, we could figure out what the differences are, but it's probably not worth it -- the details of the maps are not important, just their overall properties...
