### ISSUE TITLE
why is the mean selectivity not 0 when aspect_ratio=0 ?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#630]
Dear Bednar,

I use GCAL model to do simulation and I test different values of aspect ratio of the Gaussian patterns.
Other parameters are the same with on the Journal of Neuroscience paper.I find for aspect ratio =0, the average selectivity generated is not 0, which is about 0.1 or 0.2 or maybe larger. Why does this happen, please ? I have not understood it.

**Comment by jbednar** [comment]
For an aspect ratio of 0, presumably the input patterns would be blank, so the selectivity would be determined by the initial random weights.  

Maybe you mean an aspect ratio of 1.0, i.e. circular Gaussian patterns?  In that case, you should study the afferent weights on a projection plot, and you'll see that there are small differences in how the circular weight pattern is stored in the weights for each neuron.  In some neurons, the weights will be in the very center, and in others, particularly near the borders, the weights will be slightly offset.  For any finite retina density, the result will be slightly varying responses to patterns of different orientations, and hence non-zero selectivity values.  You can reduce those effects by increasing the retina density and LGN density, but they will never completely go away.

**Comment by windform2015** [comment]
Yes, I asked both of  aspect ratio =0 and 1, thanks for your answer. I have been thinking about your suggestion.
