### ISSUE TITLE
ipython notebook tutorial GCAL_Tutorial.ipynb issues

### ISSUE THREAD

**Issue by mjabri** [ioam/topographica#631]
While waiting on the GUI issue to be resolved, I thought i try the notebook tutorials. When trying to run the GCAL_Tutorial.ipynb tutorial it runs into import issues. Is this tutorial supposed to run out of the box? Note i am using a git clone of topographica. 

I tried:
- without touching my PYTHONPATH running from the doc/Tutorials directory/
- putting the topographica path in my PYTHONPATH - Then it cannot find 'param'
- putting the externals paths in my PYTHONPATH - Still cannot find param...

It seems the modules definitions and paths are not defined and ipython cannot find them.

**Comment by philippjfr** [comment]
How are you running the notebooks? Topographica has a notebook command for the command line, which will set up the environment correctly. Try:

```bash
./topographica -n
```

**Comment by mjabri** [comment]
Great thanks.

**Comment by mjabri** [comment]
All seems to work in tutorial until the command 

topo.sim.Retina.input_generator.anim(50)

which fails with output:

KeyError
None

If i change the value 50 to anything other than 0, it produces same error. If use anim(0) i get a pattern displayed.

**Comment by mjabri** [comment]
After further investigation, it seems the actual call to anim(50) is not the problem. So if I do:
myv = topo.sim.Retina.input_generator.anim(50)
I can examine myv and display all the maps one by one by typing myv[n]. But it seems displaying the lot by simply typing 'myv' is triggering the "KeyError \n None". Am I supposed to see a tiled view of the input patterns (0 to 50)? 
BTW Other than that, all to seem to work ok in the tutorial.

**Comment by philippjfr** [comment]
I found out the issue and will file an issue with HoloViews. For now though you can remove the call to:

```python
holoviews.archive.auto()
```

This call tries to archive all the plotted figures in the notebook and seems to be failing in this particular case.

**Comment by mjabri** [comment]
Thanks Philipp. That seems to do the trick and now that tutorial can work and I can see the animation. Cool... I think the Notebook is a good approach, but it will require me to change my entire present work flow. Something I will invest in eventually, but first I need to work out ways to take advantage of GPUs in the settling sheets, so i am stuck with the inability to display projections in the GUI if I am to look at integrating the sparce/GPU work somehow.
