### ISSUE TITLE
coord_mapper seems to confuse sparse matrix creation in sparse implementation

### ISSUE THREAD

**Issue by mjabri** [ioam/topographica#641]
Issue discussed here https://github.com/ioam/topographica/issues/640 and can be reproduced using gcal_sparse.ty.

**Comment by mjabri** [comment]
Ok, I think i found the problem and validated my fixes with gcal_sparse.ty with and without coord_mapper. So now all initial weights with and w/o coord_mapper and on sparse and non-sparse all all identical, and results (activities and weights) after 10000 iter are same.
I will merge all my changes (incl. getting gpu weights back to host) once I am on latest release and will raise a pull request.

**Comment by philippjfr** [comment]
Okay, sounds great. I still haven't been able to get the GUI working, which isn't helped by the fact that I recently switched to OSX and can't get Tk running without segfaulting at all. Will have to boot into linux and track the issue down. I'm looking forward to your fixes as I'm anxious to start using the GPU implementation myself for some of my larger models.

**Comment by mjabri** [comment]
Great. Thanks. Looking forward to getting to latest version.
