### ISSUE TITLE
how to get the data of circular variance for orientation tuning ?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#642]
Dear Bednar group members,
I would like to analyze circular variance of orientation selectivity, so I need to record the data of 
responses of single units to different orientations, but I have no idea which commands can do it.
I don't use GUI to plot the orientation tuning curves but run the script on the terminal. Could you 
give me some hints, please ?

**Comment by jbednar** [comment]
Can you tell me which commands you are running in the terminal, i.e. what the script is doing?

**Comment by windform2015** [comment]
Sure, the command is :  python  gcal.py. 
I am wondering what commands could be added in the srcipt to  record the data as I mentioned above.

**Comment by jbednar** [comment]
Ah, I see.  You can run "measure_or_tuning" (if you want to measure it for a single unit, using a circularly masked grating) or "measure_or_tuning_fullfield" (if you want to measure it for all units at once).  These commands are defined in the FeatureMapper submodule (see http://ioam.github.io/featuremapper/_modules/featuremapper/command.html).   If you import those commands from that file, then call them, the result should be something with data that you can unpack to see the responses to the various input patterns.

**Comment by windform2015** [comment]
Thanks so much for your clues. Howver, I still have no idea which specific command to record the data in the final step. For example, for the data of orienation selectivity, we could call measure_or_pref first, then use  "topo.sim.V1.views.maps.OrientationSelectivity.V1.last.data". How about this case, please ?

**Comment by jbednar** [comment]
I think this was just answered in a different issue, #658.
