### ISSUE TITLE
python setup.py build_ext do not put the .so modules in their respective directories

### ISSUE THREAD

**Issue by mjabri** [ioam/topographica#643]
optimized.so and sparse.so seem to be in the build folder. Are we supposed to copy them manually to their respective folders?

**Comment by philippjfr** [comment]
Hmm, that shouldn't be the case and seems to work correctly for me. I'll have to look into it, for now copying them manually should work though.

**Comment by mjabri** [comment]
Yes, i have been copying them manually.

**Comment by philippjfr** [comment]
This should have been fixed since adding the setup.cfg at the root level, which forces the extensions to be built inplace.
