### ISSUE TITLE
Training SOM

### ISSUE THREAD

**Issue by Hima-Mehta** [ioam/topographica#647]
Hello all,
Is it Possible to connect an array with the sheet using `topo.simulation.connect` ?
If not how can i train my SOM using not square matrix pattern i.e 400 examples each is vector of size 4.
and I want 400 gaussian outputs one for each example

**Comment by jbednar** [comment]
I'm not sure what you're asking, but  topo.sim.connect should allow you to connect any sheet to a SOM, and the input sheet will have an `activity` array.  The matrix does not need to be square; you can set whatever size you like when you create it.  If you want a vector of size 4, presumably you want individual control over each number in the vector, not a spatial Gaussian pattern as in our examples, but you can do that by making a special PatternGenerator that uses an array of NumberGenerators.  Shouldn't be much code, but I haven't ever tried it!

**Comment by Hima-Mehta** [comment]
Thanks ! I did it taking as Pattern generators of various `pattern.constant` patterns and masking it with my pattern.
