### ISSUE TITLE
Topographica and Ipython notebook

### ISSUE THREAD

**Issue by Hima-Mehta** [ioam/topographica#650]
Hello 
I am trying to Integrate my topographica code with my python inputs in notebooks.
I am using windows 7 . While importing topo I am getting following error . It was working few minutes back.! It keeps giving Different errors at anytime related to missing definition or package . what is the way to check everything is up to date ! and yes my notebook runs on Jupyter.
![capturess](https://cloud.githubusercontent.com/assets/17156030/13567072/0dc0925e-e47f-11e5-906d-042edd680559.PNG)

**Comment by philippjfr** [comment]
Could you confirm which install instructions you followed?

**Comment by jbednar** [comment]
Those look like outdated versions of the libraries; there's no `constanttime` in `imagen/__init__.py` anymore.  Probably you're mixing incompatible versions.   The latest versions of all the libraries (topographica (via github), param (via pip or conda), and imagen (via pip; conda version coming soon)) should work, or else the versions from the last official release 0.9.8.

**Comment by Hima-Mehta** [comment]
I have installed all packages via pip and my python version is 2.7.11

**Comment by jbednar** [comment]
Maybe try "pip install --upgrade topographica"?  If that doesn't work, please report the versions of topographica, param, and imagen that you have installed, e.g. by importing them and printing the `.__version__` attribute.

**Comment by Hima-Mehta** [comment]
Well , yes I upgraded imagen(2.0.1) ,param(1.3.0) separately and problem solved !  upgrading topographica gives me
imagen(1.0.1) and param(1.1.0)  which causes problem .

**Comment by Hima-Mehta** [comment]
Could you tell me the versions of libraries used in `som_retinotopy.ipynb` ? 
I have my SOM working with topographica 0.9.8 but how can I use  .grid() to see my plots without GUI.!  If holoviews support that please tell me compatible version.

**Comment by jbednar** [comment]
We don't use different versions for different notebooks, in general; usually the notebooks all come together with a particular Topographica version, and all of them should work with the same underlying libraries.  Certainly the som_retinotopy.ipynb that's distributed with Topographica 0.9.8 should work with the libraries used by 0.9.8.  It may be that the very latest som_retinotopy.ipynb on github needs to be updated to work with the latest versions of holoviews and featuremapper, but if you stay on 0.9.8 consistently everything should work.
