### ISSUE TITLE
setting the numble of cores used by the gcal python script 

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#659]
Hi I run python jobs in cluster but a single job uses more than 1 core, which may slow down other
people's jobs and also may not be so fast as it running by one core. But I haven't found out how to set the limit number of cores in python scripts or by cluster job submitting. Could you provide a suggestion for solving this problem ?

**Comment by philippjfr** [comment]
You can set the ``OMP_NUM_THREADS" environment variable.

**Comment by jbednar** [comment]
In our experience (last tested several years ago), we got very good speedups from the first few cores, up to 8 or so, and then not so much.  But it depends very strongly on the memory bus architecture of the machine, and if it's a relatively recent machine there may be a point to using more threads.  But in any case, you can limit the number stolen by setting e.g. OMP_NUM_THREADS=3 before launching your runs.

**Comment by windform2015** [comment]
For the parallel queue system in the cluster, except for setting the OMP_NUM_THREADS environment variable, do I need to add something in the script specially for the parallel processing ?  I am not sure
currently the jobs run correctly, because I set the number of OMP_NUM_THREADS as 10, but a single
job uses only 5 to 6 cores.
