### ISSUE TITLE
the half wave rectifying function

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#667]
Dear Bednar,

I would like to ask, for the function of responses of LGN units defined in J.Neuroscience paper(2013),
you use a half wave rectifying function which ensures the responses are positive, is this function to 
let negative values become zeros or the absolute values ?

**Comment by windform2015** [comment]
Since I found some different definitions about the half wave rectifier function.

**Comment by jbednar** [comment]
Zeros.
