### ISSUE TITLE
new command in 0.98

### ISSUE THREAD

**Issue by kalok87** [ioam/topographica#675]
Dear developer,

Since updating to 0.98-1, my written script for running gcal.ty is problematic. Usually I run the program in command lines to do 4 things,

1) run the simulation ( using from topo.misc.ipython import RunProgress then RunProgress.run(3000))
2) measure the preference of V1 (I used from topo.command.analysis import measure_or_pref then measure_or_pref(), and then save them as array)
3) the selectivity of V1
4) the pinwheel density of V1

but after updating I cannot even find the selectivity and preference anymore, therefore I think the new update changes the name of that command. Since the new documentation is still not available, could you please tell me the new names of those operations? Thanks a lot.

Kalok

**Comment by jbednar** [comment]
Sorry; never saw this issue get opened!  I'm pretty sure nothing changed about that command, though.
