### ISSUE TITLE
orientation preference always smaller than 1

### ISSUE THREAD

**Issue by kalok87** [ioam/topographica#679]
Hallo, recently I ran gcal.ty in topographica (version 0.9.8-1), but surprisingly I found that the maximal value of op never exceeds 1. Is it a bug in that version of topographica?

Here it is how I record the orientation preference:

1) run the gcal.ty provided in the model file in GUI 
2) use measure_or_pref() 
3) run (mat1,bbox1)=topo.sim['V1'].sheet_views['OrientationPreference'].view() where mat1 is the matrix of op
4) then I use command numpy.max(mat1) to find the maximum
5) the maxima at t = 0, 1200, 9152 are 0.99, 0.9996, 0.9998, respectively.

The results at t = 9152 is shown in attachment.
![009152 50_v1_orientation_preference](https://user-images.githubusercontent.com/7377385/35584426-4c6a2c6a-05f5-11e8-91c8-7602f49a57a3.png)

Does anyone also meet this problem in version 0.9.8-1, or just I have this situation...

**Comment by jbednar** [comment]
Like many quantities in Topographica, the orientation preference is defined as a magnitude, which explicitly ranges from 0.0 to 1.0.  For orientation, 0 is horizontal, 0.5 is vertical, and approaching 1.0 returns to horizontal.  You can convert the number to degrees by multiplying it by 180, or to radians by multiplying it by pi.
