### ISSUE TITLE
implementing long range interaction in GCAL model

### ISSUE THREAD

**Issue by dancehours** [ioam/topographica#695]
Hi, I would like to ask, how to implement long range interaction in V1 in GCAL model ? By long range interaction I mean the cortical interaction between units is beyond 1 hypercolumn range. Any suggestions ?

**Comment by jbednar** [comment]
As long as you have enough memory and a fast enough machine (or are patient), just increase the lateral inhibitory connection length.  For large changes you may need to adjust the balance between the "gamma" lateral excitatory and inhibitory strength parameters.  To keep self organization working well, you'd adjust the gammas to keep the activity bubbles in response to the training patterns about the same size before and after adjusting the sizes.  But note that GCAL's mexican-hat-style lateral connectivity is only a good approximation to the net behavior under certain conditions; if you want to model realistic lateral connectivity you'll need a more nuanced approach as in the thesis at http://philippjfr.com/ . That's even more expensive to simulate, though!

**Comment by dancehours** [comment]
Hi, why did you say"GCAL's mexican-hat-style lateral connectivity is only a good approximation to the net behavior under certain conditions"?  under which conditions ?

**Comment by jbednar** [comment]
Typically under high-contrast conditions, with strong activation in the center.  See Philipp Rudiger's PhD thesis for a review of the literature, some of which is probably covered in the GCAL paper itself.
