### ISSUE TITLE
the command to get orientation tuning data

### ISSUE THREAD

**Issue by dancehours** [ioam/topographica#696]
Hello, I would like to ask, for orientation preference map the command to get the map data is 
topo.sim.V1.views.maps.OrientationPreference.last.data,
what are the commands for getting the data for orientation tuning, something like
topo.sim.V1.views.maps.OrientationTuning.last.data ?

**Comment by dancehours** [comment]
Now I know I can use measure_or_tuning_fullfield().data to obtain the data. By type measure_or_tuning_fullfield().data I get:

OrderedDict([((mpq(20,1), mpq(1,1), 100.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 100.0, 2.8797932657906435),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 80.0, 2.8797932657906435),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 60.0, 2.8797932657906435),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 40.0, 2.8797932657906435),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 20.0, 2.8797932657906435),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 0.0), :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 0.2617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 0.5235987755982988),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 0.7853981633974483),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 1.0471975511965976),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 1.308996938995747),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 1.5707963267948966),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 1.832595714594046),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 2.0943951023931953),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 2.356194490192345),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 2.617993877991494),
              :Image   [x,y]   (Response)),
             ((mpq(20,1), mpq(1,1), 10.0, 2.8797932657906435),
              :Image   [x,y]   (Response))])

​

**Comment by dancehours** [comment]
How to obtain the data for responses from this OrderedDict?

**Comment by dancehours** [comment]
@jbednar @philippjfr

**Comment by jbednar** [comment]
At some time I would have known the answer to that, but I'd have to dive in to remind myself what it might have been, so hopefully you can find it.
